#! /bin/sh

#Let .xinitrc take car of ploybar
xset r rate 250 25  &
xinput set-prop  DELL083F:00\ 04F3:3088\ Touchpad libinput\ Tapping\ Enabled 1 &
nmcli c monitor &
nitrogen --restore &
picom --config $HOME/.config/picom/picom.conf &
$HOME/.config/polybar/launch.sh

#Change the default X cursor
xsetroot -cursor_name left_ptr

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -a I II III IV V VI VII VIII IX X
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        6
bspc config window_gap          2

bspc config top_padding         70
bspc config bottom_padding      35
bspc config left_padding        24
bspc config right_padding       24

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true
bspc config pointer_follows_focus false

bspc config automatic_scheme alternate

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a XClock:xclock state=floating
bspc rule -a Zathura state=tiled
