#! /bin/bash

eth_info=$(ip link show enp2s0 | awk 'NR==1{print $9}') 
if [[ ${eth_info} = "UP" ]]   
then
    eth_stat="up" 
else 
    eth_stat="down"
fi

wln_info=$(ip link show wlan0 | awk 'NR==1{print $9}') 
if [[ ${wln_info} = "UP" ]]   
then
    wln_stat="up" 
else 
    wln_stat="down"
fi

